/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;


import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class CadastroAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAdministrador
     */
    public CadastroAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoLogin = new javax.swing.JTextField();
        Confirmar = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CampoSenha1 = new javax.swing.JPasswordField();
        CampoSenha2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(351, 222));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 10, 70, 20);

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel3.setText("Login:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 40, 70, 40);

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 80, 70, 40);

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNome);
        CampoNome.setBounds(230, 10, 110, 20);
        getContentPane().add(CampoLogin);
        CampoLogin.setBounds(230, 50, 110, 20);

        Confirmar.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(Confirmar);
        Confirmar.setBounds(170, 180, 100, 31);

        Sair.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(281, 180, 60, 31);

        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel5.setText("Confirmar Senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 120, 160, 40);
        getContentPane().add(CampoSenha1);
        CampoSenha1.setBounds(230, 90, 111, 20);

        CampoSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenha2ActionPerformed(evt);
            }
        });
        getContentPane().add(CampoSenha2);
        CampoSenha2.setBounds(230, 130, 110, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/livros-sobre-empreendedorismo-1024x640.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSenha2ActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        
     int i =0;   
     int j =0;   
       if (Arrays.equals(CampoSenha1.getPassword(), CampoSenha2.getPassword())){
            
               
        }else{
           
            j=1;
        }
        if("".equals(CampoNome.getText())){
            i=1;
            
            
        }
        
        
        if("".equals(CampoLogin.getText())){
           i=1;
        }
        
        
        if(CampoSenha1.getPassword().length == 0){
           i=1;
        }
        
        if(CampoSenha2.getPassword().length == 0){
           i=1;
        }
         apagarCampo(); 
         if(i==1 ){
             JOptionPane.showMessageDialog(null, "Há campos vazios");
         }if(j==1){
             JOptionPane.showMessageDialog(null, "Senhas incompatíveis"); 
            apagarCampo();
         
        } if(i==0 && j==0){
        MenuAdministrador e = new MenuAdministrador();
        e.setVisible(true);
        e.setResizable(false);
        e.setSize(400, 315);
        e.setLocationRelativeTo(null);
        this.setVisible(false);
         }
         
    
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        int a =  JOptionPane.showConfirmDialog(null, "deseja cancelar a alteração da senha?","SistemaOteca",JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
       MenuAdministrador e = new MenuAdministrador();
        e.setVisible(true);
        e.setResizable(false);
        e.setSize(400, 315);
        e.setLocationRelativeTo(null);
        this.setVisible(false);
        }else{
            apagarCampo();
        }
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAdministrador().setVisible(true);
            }
        });
    }
    public void apagarCampo(){
        CampoSenha1.setText("");
        CampoSenha2.setText("");
        CampoNome.setText("");
        CampoLogin.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoLogin;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JPasswordField CampoSenha1;
    private javax.swing.JPasswordField CampoSenha2;
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
